# This is the main configuration file for your Dancer2 app
name: "Herbist"
layout: "main"
template: "template_toolkit"

engines:
  template:
    template_toolkit:
      start_tag: '<%'
      end_tag:   '%>'

show_errors: 1
